### ISSUE TITLE
Create examples in SPL or DS

### ISSUE THREAD

**Issue by omarkdev** [mirahman/PHP-Data-Structure-and-Algorithms#6]
I was taking a look at your examples and I really enjoyed it. However, I have seen that you do many things manually which can be simplified with some things that PHP has in [SPL](https://php.net/spl) and [DS](https://php.net/ds), what do you think if we create examples using their libs? 

I think it's a really good idea because you have a lot of examples, thing PHP don't have. If we can create more examples and in the future create a documentation and define the documentation and examples in PHP docs.

The data structures are really essential, we need start talk more about that!

**Comment by mirahman** [comment]
Hi

i agree with you. the reason i wrote own implementation is that, the book i wrote "PHP 7 Data structures & Algorithms" has the approach of doing things from Scratch. in some places i have shown how to do it using SPL and DS. 

In general, i will prefer using DS compared to SPL. 

Lets create another branch and create similar examples using the DS library. I will be happy to help :)
